### ISSUE TITLE
Determine the primary work email for an identified person

### ISSUE THREAD

**Issue by zurk** [src-d/identity-matching#29]
Related issue: Determine a primary name for an identified person https://github.com/src-d/eee-identity-matching/issues/28

The motivation is the same as in #28: we want to know the primary email and not just an id. 
It looks like different approaches will work for name and email, so there are two issues for both of them

Plan: 
Plan:
- [ ] Get the data for proper validation. We may use Github API but many users do not keep email publicly available 
- [ ] Test simple heuristics like 
    - [ ] take the most frequent email without blacklisted host like gmail, inbox, etc (it is more personal emails). 
    - [ ] ???
- [ ] If simple heuristics do not give good performance train something like GBDT.

**Comment by vmarkovtsev** [comment]
Please note: when calculating the stats, we should take into account only the last year. If there are too few commits in the last year - then the last two years, and etc.

**Comment by vmarkovtsev** [comment]
@irinakhismatullina Can you please create another issue to add the last year filter.
