### ISSUE TITLE
Alter Docker image so it dumps output to a defined folder

### ISSUE THREAD

**Issue by alexpdp7** [src-d/identity-matching#87]
Later preprocessing steps in sourced-demo rely in the Parquet files generated by this. Right now if you use the `Dockerfile`, they are dumped to `/`, which is not convenient.

The simplest solution would be to dump them to a fixed directory (e.g. `/data`), probably adding `WORKDIR /data` to the `Dockerfile` before running `identities2sql.sh` would work. If you want to get fancy, you can get the path from an environment variable.

This would allow us to bind-mount this folder in both identity-matching's container and preprocessing.

Depends on https://travis-ci.com/src-d/sourced-demo/builds/132103418 passing, though.

**Comment by vmarkovtsev** [comment]
On this.

**Comment by vmarkovtsev** [comment]
@alexpdp7 I believe that if you define `IDENTITY_MATCHING_OUTPUT` to `/data` then it will work out of the box.

**Comment by alexpdp7** [comment]
Doh, I'm dumb. I'm on it...

**Comment by alexpdp7** [comment]
Yeah, you can close this. https://github.com/src-d/sourced-demo/pull/97/commits/31e7b89d2173476bf88198a99f8e54a76ab4f085 seems to work
