### ISSUE TITLE
Performance dropped critically

### ISSUE THREAD

**Issue by warenlg** [src-d/identity-matching#91]
I've been benchmarking the performance of `match-identities` and figured out I was not able to process some orgs I used to process pretty quickly 2 months ago. For example, `digitalocean` used to take me 3sec, now it is hanging forever. The step that is hanging is `reducing identities`.

The drop has been introduced between `v2.0.0` and `v.3.0.0`. After going through the commit history, I figured out the drop started at this [commit](https://github.com/src-d/identity-matching/commit/50d9c6d7639b6ec0a645a1211ed9af31763a5465) when adding the primary name feature.

The list of git signatures to process includes duplicates (to get the frequence), then commit_date and then commit hash. So, we pass from:
* 1907 to 45287 signatures for `src-d` and from 1sec to 60sec (CPU time) to process
* 57K to 1.77M signatures for `digitalocean` and from 3sec to forever (CPU time) to process

If we want to keep this feature, we might want to optimize this a bit.

**Comment by irinakhismatullina** [comment]
I've looked through the commit, on the first sight the only affecting thing may be [this](https://github.com/src-d/identity-matching/commit/50d9c6d7639b6ec0a645a1211ed9af31763a5465#diff-0c70f2fe4e8e15be02dbfbc9893cf1e5R363).

Here instead of selecting `DISTINCT` commit signatures, they select all of them to count the stats. If after that no deduplication was added, and all unique commit signatures are now considered as identities, this may lead to such effect...

**Comment by irinakhismatullina** [comment]
It is easy to check - if after adding this single `DISTINCT` [here](https://github.com/src-d/identity-matching/blob/master/people.go#L403) performance improves, this is it and we know what to fix:) 

@warenlg Is it easy for you to try it in your experiment set up?

**Comment by warenlg** [comment]
Yes this brings back the good old performance but indeed, `DISTINCT` would be useless today since we collect the `commit_date` and above all `commit_hash`.
We have to  look if `commit_hash` is really useful, store the `commit_date` more efficiently (maybe for example, all dates in the same row, instead of duplicating name, email each time) and we gave to check if there is not a hidden quadratic complexity somewhere.

**Comment by irinakhismatullina** [comment]
Awesome!

Do we really collect `commit_hash`? Haven't seen it at all.

As to `commit_date`, nothing complex is required, the dates can be discarded right after stats calculation, and this is always done before reducing, so deduplication can be added easily and the performance will be shiny.

**Comment by vmarkovtsev** [comment]
Yeah we collect hashes because we need them for GitHub API.

**Comment by vmarkovtsev** [comment]
I fixed this with the GROUP BY as I suggested.

**Comment by warenlg** [comment]
Just tested the performance again, and indeed it runs way faster now
